<?php

namespace App\Http\Requests\Academics;

use Illuminate\Foundation\Http\FormRequest;

class LessonAddRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'title' => 'required|string|unique:academic_lessons,title',
            'descriptions' => 'nullable|string',
        ];
    }

    public function messages(): array
    {
        return [
            'title.required' => 'title tidak boleh kosong',
            'title.unique' => 'title harus unik, tidak sama dengan data sebelumnya',
        ];
    }

    public function validateWithBag(string $errorBag, array $rules, ...$params): array
    {
        parent::validateWithBag($errorBag, $rules, $params); // TODO: Change the autogenerated stub
    }

}
